### ISSUE TITLE
how to sponsor?

### ISSUE THREAD

**Issue by Maxhodges** [vuejs-jp/home#1]

**Comment by kazupon** [comment]
Hello :)

Thank you for your interest in our community!
I'm vuejs-jp organizer.
I'm interested in your sponsorship.
Where can I meet in Tokyo?

**Comment by kazupon** [comment]
Hi! @Maxhodges 
We had published Vue Conference Japan teaser site.
If you are interested in sponsor, We'll be waiting. :)

**Comment by kazupon** [comment]
We'll be anytime waiting. :)
