### ISSUE TITLE
インフラを選定する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#11]
**UPDATED: 2019.08.19**

実装完了（デプロイ時）までにより良いアイディアがでない限り、Netlifyへデプロイする方針とする。

---

公式ウェブサイトを稼働させるインフラを決定します。今後イベント情報の取得、ニュース一覧など動的な機能が多く追加されることを考えると、SSRで稼働させる可能性も考慮する必要あり・・・？　個人的にDigitaloceanなどのVPS以外での運用実績が乏しく・・・。

SSRでもStaticでも対応でき、動的な仕組みも取り込みやすい最適なインフラとかご存知のスーパー技術者の肩の意見が欲しいです！

期日までに結論が出ない場合、一旦StaticベースでNetlifyやGitHub Pagesにデプロイすることにしたいと思います。

**Comment by kiaking** [comment]
インフラ選定における考慮すべき項目を考察。

まず、管理コストの観点からServerless（NetlifyやFirebase）が望ましい。完全に静的なサイトであれば問題ないが、想定される将来的要件を満たすことが可能か？

### お問い合わせフォーム

初期リリースで必要。Netlify Formなどが有力。

Ref: https://github.com/vuejs-jp/home/issues/15#issuecomment-516828175

### News & Events

Vue.js 日本ユーザーグループのnoteやconnpass、地域コミュニティなどの外部サイトからのAPIによる取得がメインになるはず。これらはリアルタイムに掲載されているのが理想だが、不定期に更新される外部サイトの情報を静的サイトで実現可能か？ Netlify Functionなどを使えばいけるものなのだろうか・・・？ その場合サーバサイドでキャッシュとかできるのか？ 過去の記事も含め、アーカイブしていきたいという要望があった場合、バックエンドにDBが必要になったりしないか？

### ギャラリーページなどのアーカイブ系

例えば過去のMeetupの様子の写真だったり、登壇資料などが閲覧できるページがあると嬉しい。これはまぁ静的サイトとしてジェネレートすれば良し。

### 現時点でのアイディア

NewsやEventsのようなリアルタイムに更新される動的なコンテンツをどうするかが自分の中で不透明。Netlifyで上手くやれる可能性があるならそれで良いという気持ち。

仮にNetlifyでは難しい場合でも、その時にどこかにAPIサーバを立てて、フロントはNetlifyでサーブしつつ、必要な箇所は適時APIサーバを叩くでも実現できる。この場合SSRができなくなる（気がする）が、外部情報をSEO目的でソースに含める意義も薄い・・・か？ いや重要か・・・？

リアルタイムにデータを取ってくるのはどっちにしろビルド時にできないので、SSRが可能な環境を用意するか、あるいはSSRは必要ないと判断してフロント側でAPIを叩くようにするか...。

将来的な話なのでどうしてもふわふわしてしまうが、知見のある人からの意見がくるのを祈る・・・！

**Comment by kazupon** [comment]
要件次第では、v1.0 がリリースされた VuePress もありかもですね。
VuePress 、基本ドキュメントに特化された static site generator ですが、plugin アーキテクチャになったので、データの扱いは縛りがなくってそうです。

**Comment by kiaking** [comment]
@kazupon 確かに！ 特に過去のイベント情報の掲載とか、決まったフォーマットで書いていく系のページはVuePressでMDでサクサク書くみたいなのは気持ち良さそうですね。

デザイン並行して進めつつ、引き続きここで検討できればと思います・・・！

**Comment by kiaking** [comment]
さらに考えを進めたのでメモ。

真にリアルタイムなコンテンツ、例えば直近のイベント情報や外部のニュースなどは、そのような手法にせよ構造的に綺麗に管理するのは困難。例えばページングがあって過去の情報がずっとみれて、みたいな。そのため、結局はフロント側でAPIを叩いて取ってくる形になると思う。そういう意味でSEO目的などでSSRする意義も大きくないと思われる。

そう考えると、運営側で手動で更新する内容、例えば過去のイベントで発表されたスライドとか、イベントの写真とかそういうのはコード上にJSONとかで持っておいてもいいし、Netlify CMSだったりContentfulを使っても良い。何れにせよ更新されるごとにビルドしてしまえば十分。

基本的に当サイトはウェブサイトであり、管理機能や予約機能がゴリゴリついたウェブアプリにはならないだろうし、SSRが必要になる状況も現時点では考えにくい。

仮に将来的にログイン機能とかまでついていい感じの何かしらの機能がつくとしても、もうぶっちゃけその時考えるしかない。

よって、現段階ではNetlifyか、あるいはGitHub Pagesにデプロイする、という案が僕の中では優勢。サイトデザインをやりつつ、引き続き思い悩んでみる。

**Comment by kkyouhei** [comment]
主要なPaaSにOSS向けの無料枠があるか問い合わせで聞いてみましたが無いとのことでした

**Comment by kiaking** [comment]
@kkyouhei うおお問い合わせまでありがとうございます！ 週末も考えてみましたが、この感じだとやはりNetlifyですかねぇ。

ひとまず、デプロイを本格検討するまでまだ時間があると思うので、一旦ある程度サイトが出来上がるまでNetlifyで稼働させる前提で進めようと思います。

その間に良いアイディアなど上がってくれば、都度検討するということで！

**Comment by shiba328** [comment]
遅レスですみませんが、話の流れを見てると、要件としては

- お問い合わせどうする？
- 外部API取り込みたい
- MDで書きたい
- 記事部分どうする？cms入れるほどじゃない？静的で良い？
- ホスティングどうするか？

ってところですかね？

実装方法が気になったのですが、

### お問い合わせどうするか
デザイン性考えなければ、googleフォームが1番楽だし、せっかくのvuejsなんだから、GAS使ってspreadsheetに直接書き込んでも良いんじゃないの？とは思いましたが、scriptの管理が複雑になるので、現実的では無いか。

### MDで書きたい
想定されてるのは、nuxt/markdown-itでコンポーネント読み込みですか？


### 外部API取り込みたい
各サイトのAPIをaxiosで叩いてStoreで整形して日付順一覧に出す。でも良いのでは？と思いました。(自分の認識ずれてそう)

### 記事部分どうする？cms入れるほどじゃない？静的で良い？
記事の投稿をcmsなしオッケーなら、記事自体はnuxtの動的routingですかね？
アーカイブは、とりあえず全記事一覧json書いて内部で呼び出せば良いですか？

### ホスティングどうするか？
circleci噛ませればどのホスティングでもデプロイできるので、一旦githubにまとめておけば良いのでは？

### その他
ユーザーから直接コンテンツを集めるわけではないので、cms化は今のところ不要だろうなーと思いました。ただSlackに質問が来て、解決した問題をアーカイブ出来たら良いのになっと思うことがあります。

以上です。

**Comment by kiaking** [comment]
@shiba328 コメントありがとうございます！ 現状Netlifyで静的サイトかなという感覚が強いので、概ね記載いただいた内容かなと思っています。個別の実装については別途個別機能実装のIssueでディスカッションできればと考えています。

唯一僕が懸念していたのは、外部APIの部分で、地域のVue.jsコミュニティだったり、外部のニュースをリアルタイムにサイトに表示しながら、ページングやアーカイブまでしたい、みたいなケースがあった場合、バックエンドでDB持ってないと無理だよね、という点でした（外部のページから情報が消えてもVue.js JPのサイトで過去の情報をみれるようにする的な）。この場合むしろGCPでFirebaseを活用する、みたいな可能性もあるかなと。

が、ぶっちゃけ少なくとも現状そこまで必要ないと思っているので、

> 各サイトのAPIをaxiosで叩いてStoreで整形して日付順一覧に出す。

で良いと僕も思っています。

という事で、現状は何か他にグレートなアイディアが出てこない限り、Netlifyにデプロイする前提で進められればと思います！ 👍

**Comment by kazupon** [comment]
@kiaking 
netlifyを使う想定だと思うんですが、こんな感じでPRが来はじめているので、導入してGitHub の CI/CD に対応させておきたいです。
https://github.com/vuejs-jp/home/pull/38

PRレビューするときも、サイト確認できるので。

**Comment by kiaking** [comment]
@kazupon やりたいですね！ やりましょう！ 別途Netlifyのセットアップとか相談させてください。

**Comment by kiaking** [comment]
本件、インフラ環境のためコアスタッフでの議論にて、Netlifyに静的デプロイでいこうという感じになりました。ひとまず、ステージング環境を用意し、開発中のものを公開できればと思います。本Issueは、Staging環境ができたら閉じる、イメージで。

@mtmtkzm よろしくお願いします！

**Comment by mtmtkzm** [comment]
@kiaking  @kazupon 

document のレスポンスヘッダーに `x-robots-tag: noindex` があるため、ステージング環境はインデックスされるなどの心配はなさそう（？）。だが、プロダクション環境ではそれがないため、開発中のものがインデックスされ、意図しない情報（リアルなダミーテキストなど）が拡散する恐れがある。

対策として下記はいかがでしょうか？

（そういうもんだよ！って感じなら読み飛ばしてください！ :joy: ）

## 1. master に Nuxt を用意
ステージング環境を用意するにあたって、
「`yarn generate` が Netlify で実行できる」かつ「公開して問題ない状態」のプロダクション環境を準備する必要があるためです。

develop にあるこの辺りのコミットまでを master へマージしてしまってもよいのかなと...真っ白な画面ですが...！

https://github.com/vuejs-jp/home/tree/5ac6f65f62c6ab5ce98d97ec0492de67874a4c95

## 2. Netlify に GitHub リポジトリを紐づける

- Branch to Deploy: `master`
- Build Command: `yarn generate`
- Publish directory: `dist`

**Comment by kiaking** [comment]
@mtmtkzm 貼ってもらったコミットマージで良いと思います！ 対応お願いできますか 😎

**Comment by mtmtkzm** [comment]
@kiaking  @kazupon 
master を整えました。
#41 マージしたので、Netlify の設定をお願いできますでしょうか？（いつも通りの設定です。）

- Branch to Deploy: master
- Build Command: yarn generate
- Publish directory: dist

Pull Request ごとの確認環境はデフォルトで準備されるようですが、
PRに関係ないブランチ（今回は develop をいつでもみたい？）でも確認環境を準備したいため、
下記項目も設定おねがいいたいます！

`Build & Deploy` > `Continuous Deployment` > `Deploy contexts` > `Branch deploys` : **All (Deploy all the branches pushed to the repository.)**

`develop` => `master` でPRだしておいてもいいのかもしれませんが...

**Comment by kiaking** [comment]
@kazupon ﾀﾉﾝﾀﾞー

> develop => master でPRだしておいてもいいのかもしれませんが...
これはとりあえずやっておいて良さそうですね！

**Comment by kazupon** [comment]
@kiaking @mtmtkzm 
設定しました。URLはこちら 
https://naughty-payne-398e17.netlify.com/

**Comment by kiaking** [comment]
@kazupon Thanks! 👍  動いているっぽいですね。あとはPR出したらプレビューリンクができる・・・のかな？ 試してみて問題なさそうならIssueクローズの方向で動きまっす。

**Comment by mtmtkzm** [comment]
`develop` => `master` でだしてみました。

そしたら確認環境でてきましたー！わーい
https://deploy-preview-42--naughty-payne-398e17.netlify.com/
