### ISSUE TITLE
ドメインを確認する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#13]
@kazupon @inouetakuya Vue.js 日本ユーザーグループのドメインってありますか？ 😳

**Comment by inouetakuya** [comment]
え、どうなんだろう？たぶん、無いような... 

ちょっと分からないので @kazupon にパスします 🙏

**Comment by kazupon** [comment]
ドメインないですね...
vuejs.jp も取られてるし...
https://vuejs.jp

新しく考える必要があります。

**Comment by kiaking** [comment]
おお、そうなんですね。Vuejsがorgなのを加味して、 `vuejs-jp.org` ですかねやはり。GitHubのOrganization名もそうだし。いかがでしょう？

**Comment by kazupon** [comment]
`vuejs-jp.org` 、よさそうです！

**Comment by kiaking** [comment]
@kazupon 確認ありがとうございます！ では、おそらく反対意見でない気がするので、 `vuejs-jp.org` でドメインの確保お願いできますか？ 🤝  リリース間近になったらDNS周りの設定お願いさせてもらえればと思います。

**Comment by kazupon** [comment]
@kiaking ドメイン確保しましたー

**Comment by kiaking** [comment]
@kazupon ありがとうございます！ では、ローンチ近くなったらまた別途設定と依頼します。ありがとうございました！
