### ISSUE TITLE
ロゴを選定する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#14]
Vue.js 日本ユーザーグループのロゴを作成する。現在のGitHub Organizationsで利用しているロゴの可能性もあり。

ロゴデザインは任せろ！ というかた、ぜひ！ 🥇 

参考: [Vue.js ベルギーコミュニティ](https://vuejs.be)

---
> 過去の投稿

@kazupon @inouetakuya 

公式ウェブサイト、あるいは色々な所に使うロゴを選定します。個人的にはGitHub Organizationsで利用しているロゴを使っていくのシンプルで良いかなと思ってますがどうでしょう？

もっとがっつり日本ぽくするアイディアもありつつ、今のロゴはよりVueとコネクトされてる感があって好きです（別物ではない感じ）。参考として[ベルギーのコミュニティ発見](https://vuejs.be)。

現状のロゴでOKそうならロゴデータをどこかで共有いただければ幸いです！（ロゴとかブランドデザイン系を格納するGitHub Repo作ります？

**Comment by kazupon** [comment]
@kiaking 
今のロゴは、当時vuejs-jp立ち上げたメンバーで、ロゴに対する想いとか特に議論もせずに、Vueロゴに`jp` 載せておけばいいでしょ？っていう感じで作ったものですね。
ロゴの元データどこにあるのかもわからない状況です。

個人的には、今回がいいタイミングなので、新しくロゴ作ってもいいかなと思っています。

**Comment by kiaking** [comment]
@kazupon なるほど。ありがとうございます。確かに、最終的に現在のロゴに近くなったとしても、検討はやってみて良さげですね。

ということで、ロゴデザインやってみたいかた・・・ぜひ！ 僕の方でもちょっと考えてみます。

**Comment by unotovive** [comment]
外部から失礼します。VUEJS AMSTERDAMのようにロゴの色のみを変更するというのはどうでしょうか？淡めの桜色とか日本感あって良いかなと

**Comment by tatsuya-akitsu** [comment]
失礼致します。
Nuxtのロゴのようなイメージで、VueのVを少し桜っぽい花弁にアレンジしたものを重ねたロゴとかはいかがでしょうか。
Vueということが伝わる必要もありますので、色味と崩し方は調整が必要かと思いますが…！

**Comment by fukiwatanaebe** [comment]
外部からいきなり失礼いたします....！Roppongi.vueというグループのロゴを担当したものです。
会社の方からこんなの募集してるみたいですと共有いただいたのですが、興味があります...！
もしデザイナーに委託したいという形でしたら、お力になれたらと思います。

**Comment by kiaking** [comment]
みなさんご意見ありがとうございます！

---
@unotovive @tatsuya-akitsu 
Vue Amsterdam、ナイス情報ありがとうございます。ロゴ自体の色味を変えることについては、ロゴの色によってサイト全体のプライマリカラーが変化することを懸念していました。[原稿のラフデザイン](https://projects.invisionapp.com/share/Q3T7OZ8XVE6#/screens/376395960_Idea--A--001)では、ボタンの色など、全体的にVue公式のスタイルと親和性を持たせることを重視しました。例えばロゴが桜色とかになる場合、全体的に桜色になるかなと。

また、Vue Fes Japanや上記Vue Amsterdamなどのカンファレンス系は、Vueに限らずどこのイベントも毎年がっつりデザインが変わるため、そこでVue公式のスタイルからかけ離れるのは全く問題ないと考えていますが、Vue.js 日本ユーザーグループの定常的なサイトとしては、Vueと親和性があった方が良いのではないか、とも考えています。また、公式ウェブサイトに限らず、Tシャツやキーノートスライドなどの販促物のデザインにも影響してくるかなと。

そういった意味で、[Vue.js Belgium](https://vuejs.be)のように、Vueのロゴの横に日の丸であったり、桜といった日本テイストを付加するという形は、上記の懸念点であるサイト全体のスタイルに影響を与えない（例えばボタンは緑のままでいける等）メリットがあり、個人的にも良いアイディアだと思っています。

まとめると、個人的な見解としてはVue Logoの色と形は維持した状態で、アクセントを加える方式、が良いのではと思っています。もちろん個人的見解のため、なにがなんでもそうする、ということではなく、ぜひみなさんご意見を伺いたいです。

上記観点、サイト全体の配色に与える影響、Vue公式への寄せ具合、といった観点からのご意見はいかがでしょうか？（Vueファミリーの正式な一員感出したいから親和性重視だぜ、コミュニティなんだからぱっと見全く別物と分かってインパクトあった方がいいっしょ、色も含めて存在感出していこうぜ、等）

---
@fukiwatanaebe 
ご興味を持っていただきありがとうございます！ すごい人がきた！

委託、といっても本プロジェクトはオープンコミュニティ活動のため、金銭的な報酬はなく、またお願いしたからといって必ず @fukiwatanaebe さんのロゴが採用されることを確約できませんが、誰でもアイディアを提供できますので、もしご協力いただけるなら是非ともお願いしたいです！

**Comment by fukiwatanaebe** [comment]
全然すごいひとではないのですが、提案だけさせていただけたらと思います！具体的なラフ案の締め切りなどはありますか？

**Comment by kiaking** [comment]
@fukiwatanaebe ありがとうございます！ 締め切りですが、サイトのローンチを9月末として、ロゴによってサイト全体のデザインに影響がある可能性を考慮すると、お盆前（8/8〜9）くらいにはラフの中からこの方向で行くというレベルまでは決定できればいいなと思っています *1。そのため、可能であれば8/5週前半に第一案とかいただければ最高です。最終的な調整も含めたロゴの完成については、8月末頃までに決まっていれば十分かと考えています。

とはいえ、締め切りを重視しすぎてみすみす良いアイディアを捨てることは無いと思っていますので、無理のない範囲でご協力いただければと思います！

*1 ロゴが最終化していなくても、サイトのデザインに取りかかれるレベルで形や色の方向性が見えている状態をイメージしています。

**Comment by resessh** [comment]
ラフ案がwelcomeということで、さっくりと作ってみました。

サイト仮デザインの日の丸がプリミティブでとても良いなと思ったので、同じモチーフでレタリングしてみました。

![vue-jp-logo](https://user-images.githubusercontent.com/1481277/62293328-54fc4a80-b4a3-11e9-9e83-96401b0bf86f.png)

**Comment by kiaking** [comment]
@resessh おおおお！ ありがとうございます！ やはりものがあるとイメージがしやすいですね 👍

**Comment by kiaking** [comment]
ということで僕もラフ案を。日の丸推しで、海外の人から見ても一発で日本だと分かるように。

![logo-vuejs-jp-ideas-001](https://user-images.githubusercontent.com/3753672/62337565-1cdf2100-b510-11e9-847c-de4b3f7833b1.png)

1. シンプル・イズ・ベスト。
2. (1)をもう少し派手に。ただ大きな意味が見出せない。これなら1の方が良いかも。
3, 4. Vue Belgiumのようにもう少し存在感を。少しごちゃっとする感じは否めないが、この中では最も日本ということが分かりやすい。

引き続きみなさんのアイディア、ご意見、フィードバックお待ちしております！

**Comment by resessh** [comment]
日の丸モチーフにするなら赤の面積比少なめにすると圧が少なくておしゃれですね！

**Comment by umiremix** [comment]
Kiaさんのロゴ素敵ですね！
#1もデザイン的にはすごく好きなのですが、#4日本だとわかりやすいのと、Vue JPだと認知されやすそうなので良いな〜と思いました！
今週VueFesのグッズが大詰めなので、それが落ち着けばロゴ作れそうです。
早めに選定したいとのことでしたら私のことは無視してくださいmm

**Comment by k-miyake** [comment]
ちなみにTypeScriptコミュニティでは世界各国で国の特徴が出るようなロゴ（アイコン？）を作ってます。
https://typescript.events/

**Comment by shika358** [comment]
このTSのロゴいいですよね､日本の情緒が詰まってる感じで｡

**Comment by fukiwatanaebe** [comment]
もうすでに素晴らしいロゴがいっぱい出ているので私はもういいと思ったんですが、一応提出させていただきます....！

上がVueのロゴをリスペクトした案、
下は日本の伝統的な和柄を掛け合わせたものになります。
![vuejp提案](https://user-images.githubusercontent.com/45450527/62358661-17093000-b550-11e9-88ae-75541e8c8f7f.png)

**Comment by resessh** [comment]
右上のめちゃ好きです！

**Comment by fukiwatanaebe** [comment]
Kiaさんのデザインが大変素敵です...！
#1のシンプルデザインがとても洗練されており、いろんな媒体やレイアウトで使いやすそうで素晴らしいと思いました....！「JP」や日本であることはいずれにせよ必ずサイトのどこかに書かれるので、可読性はそこまで重視せずともいいかと思いました！

**Comment by kiaking** [comment]
みなさんフィードバック、デザイン感謝感激です！

@umiremix 
今の状況を鑑みるに、ロゴによってサイトデザインに大規模な変更が必要になる可能性は低いと思えています。ですので、思いっきり急ぐ必要もないかと考えており、ロゴお待ちしております！ 👀 

@k-miyake @shika358 
Thanks infoです！ 統一感あるし、賑やかで綺麗だしいいですね。Vue.jsも各国のコミュニティで統一できたらめっちゃオシャレそうですが・・・、まぁそれは難しいとしても、ロゴを何かで囲う発想がなかったので、検討しても良さそうだなと思いました。これらデザインは密度と複雑さの問題からいわゆるロゴとして展開していく際に障害が多そうですが、こういう賑やかなイラストやエンブレムみたいなものも別に用意して、各種イベントや販促物で使えるとオシャレかなとも思ったりしてます。🇯🇵

@fukiwatanaebe 
ありがとうございます！ 僕も右上好きですね。斜めのラインが美しくて全体的にバランスが良く、勢いがあってボールド、完成されている感が素晴らしい。Vueカラーということもあって、例えば僕のものと比べるとこちらの方がVueの公式との距離が近い印象を受けました。これは「日本感」、ならびにVue公式との距離感をどの程度表していくかという点からの検討でも、大きな参考になると思っています。🖖

---

今後の流れですが、@umiremix さんへの回答内容の通り、現状では最終的なロゴによってサイトデザインに大規模な変更が必要になる可能性は低いと判断していますので、サイトデザインは並行して進めていきます。現在色々な方がデザインを上げてくれていることもあるので、ひとまずお盆明けくらいまで引き続きアイディアを募集しようと思います。

盆明けにあまり動きが無いようにであれば選定に移り、動きが活発ならさらに期間を延長しようと思います。引き続き、よろしくお願いします！

**Comment by kiaking** [comment]
てな訳でお盆も明けたわけですが、さて、 @umiremix ロゴ、作っちゃいますか！？ |ω・`）

**Comment by kiaking** [comment]
本件、遅くなりましたが、期限が近づいてきたため、コアスタッフの中での選定に入りました。結果については、追ってこちらでご報告します！

**Comment by kiaking** [comment]
みなさん大変お待たせしました。コアスタッフの中での議論の結果、以下のロゴを選定いたしました！ 🎉 

![logo-vuejs-jp-showcase-full@2x](https://user-images.githubusercontent.com/3753672/65125420-4ad0e400-da30-11e9-8095-42202ced6e9a.png)
![logo-vuejs-jp-showcase-brandmark@2x](https://user-images.githubusercontent.com/3753672/65125421-4b697a80-da30-11e9-85ee-627a570e3f4d.png)
![logo-vuejs-jp-showcase-brandmark-guides@2x](https://user-images.githubusercontent.com/3753672/65125422-4b697a80-da30-11e9-8ce3-cad41f2866ab.png)

どれも魅力的なロゴばかりであり、検討に時間を要しましたが、大きくは以下の理由によって本決定となりました。

- 色やバランスから、日本のシンボルらしさを感じる。
- "JP"がもとのVueのロゴに寄り添うようで主張しすぎないところが､User Groupの立ち位置とリンクしている。

順次、Vue.js 日本ユーザーグループ関連のいろいろなアカウントにて、ロゴの繁栄を行なっていきたく思います！

みなさん本当にありがとうございました 🙇
