### ISSUE TITLE
Contactページを実装する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#15]
初期リリースに必要となる、Contactページの実装を行います。

- [Contact](https://invis.io/Q3T7OZ8XVE6#/377378832_Contact_-_1-0-0)
  - [Contact – Hover State](https://invis.io/Q3T7OZ8XVE6#/377378839_Contact_-_Hover_-_1-0-0)
  - [Contact – Error State](https://invis.io/Q3T7OZ8XVE6#/377378838_Contact_-_Error_-_1-0-0)
  - [Contact – Sending](https://invis.io/Q3T7OZ8XVE6#/377378840_Contact_-_Sending_-_1-0-0)
  - [Contact – Complete](https://invis.io/Q3T7OZ8XVE6#/377378837_Contact_-_Complete_-_1-0-0)

## 仕様など諸々

ディスカッション中...

**Comment by kiaking** [comment]
@kazupon Contactページって、イメージとしてVue.js 日本ユーザーグループに対する汎用的なお問い合わせフォーム、ってイメージであってますかね？

その場合バックエンドとかをどうするかな。 #10、#11にも大きく関係しそうだが、こうしたらいいんじゃない？ とかってアイディアをお持ちの方がいたらぜひ！

**Comment by kazupon** [comment]
はい。
Serverlessなら、Netlify Formですかね。
後、Google spreadsheet + GAS

**Comment by kiaking** [comment]
@kazupon ありがとうございます！ Serverlessは魅力的ですよねぇ。NetlifyはFunctionもAuthもあるし、将来に向けた拡張性も高そう。他の要件照らしつつ、できればServerlessな感じでいきたいですね。

**Comment by sukezane** [comment]
はじめまして。 Contactについて考えていたのですが、独自でフォームを実装するのではなく[drift](https://www.drift.com/)や[zendesk](https://www.zendesk.com/)などサードパーティ製のツールでContactを実装するのも一つの選択肢になりそうかなと思いました。（[vue.js london](https://vuejs.london/)はdrift使ってるみたいです）
他の要件とマッチするか、運用がしやすいかとか考慮する点もあるかと思いますが、参考になれば幸いです。

**Comment by kiaking** [comment]
@sukezane フィードバックありがとうございます！ 確かにそういうサービスを使ってしまうのもありですね。driftは知らなかったので大変参考になります。ありがとうございます。

ひとまず初期の段階では問い合わせを受け付ける、ということができればそれで良い状況かとは思いますので、実装時にいい感じに使えるツールを選択できればと思います。

いずれ多機能なものが必要になった時も含め、こういうリストはあれば助かるので、ぜひみなさんからのご意見いただければと思います 👍
