### ISSUE TITLE
Stylelintを導入する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#18]
Ref https://github.com/vuejs-jp/home/pull/17#issuecomment-522820915

Stylelintを導入し、CSSをLintできるようにする。

/Cc @shiba328

**Comment by shiba328** [comment]
vue-jpとして先達になる良い規約になるように頑張る。
デプロイまでは暫定です。
知見のある方のご意見よろしくお願いしますー！

## Nuxtへの導入手順
```
yarn add -D stylelint stylelint-webpack-plugin stylelint-config-recess-order
```
## ルールの選定
暫定：[stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)

## 検討材料
### 1. Standard以外のルールはどうする？
.stylelintrcを確認の上、足りない or Standardではないものを修正。

### 2. Orderについて
暫定：[stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order)

肥大化した場合にAlphabet orderは可視性が悪いのでproperties orderを推奨したい。

- [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order)
- [stylelint-config-rational-order](https://github.com/constverum/stylelint-config-rational-order)

※ 並び順を把握するために[twitter/recess](https://github.com/twitter/recess/blob/29bccc870b7b4ccaa0a138e504caf608a6606b59/lib/lint/strict-property-order.js
)を確認

### 3. Nuxtで保存時のAuto Lintについて
scopedをlintするのでnuxtのbuild時にvueとPostCssにauto lintを推奨したい。

**Comment by kiaking** [comment]
特に異議なしっす！

**Comment by kiaking** [comment]
っと、導入完了してましたね。ということでクローズです！ @shiba328 さんありがとうございました！ 🎉
