### ISSUE TITLE
vue-property-decoratorを利用する

### ISSUE THREAD

**Issue by shiba328** [vuejs-jp/home#22]
# このissueはなんのため？
componentのためにvue-property-decoratorを追加してください。

https://ja.nuxtjs.org/guide/typescript/#%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88

https://typescript.nuxtjs.org/cookbook/components/#template
https://github.com/kaorun343/vue-property-decorator

**Comment by kiaking** [comment]
@shiba328 Issueありがとうございます！ 本件、 https://github.com/vuejs-jp/home/issues/10#issuecomment-522409989 においてClassではなく、Object Syntaxで進めるという話となっています。

当該コメントでは、コメントがなかったために僕の決断でそうしましたが、いかがでしょう？

**Comment by shiba328** [comment]
@kiaking 
#10 に追いついてませんでした！スミマセン！
tsやるのにドキュメント読み直してたら「強くお薦め」だったのでissus立てましたが、Object Syntaxで大丈夫です！

**Comment by kiaking** [comment]
@shiba328 いえいえ！ これは僕もウルトラ悩ましいところなので...! 開発が進むにつれてObject Syntaxで不都合が出てきたら、Class Syntaxへ移行もありだと考えています 👍
