### ISSUE TITLE
Aboutページを実装する

### ISSUE THREAD

**Issue by shiba328** [vuejs-jp/home#25]
仮の実装で進めます。

機能が多いため各エリアごとにcomponent化します。

[Design Mockup: About](https://projects.invisionapp.com/share/Q3T7OZ8XVE6#/screens/377814092)

**Comment by shiba328** [comment]
kkyouheiさん
cc @kiaking 
一旦 ABOUTページのマークアップだけのモックをコミットします。

■ 注意点
- slide/History/staffは、今後DBからの取得になるかも？も考慮して、computedで直接書いて実装しましたが、後ほどjsonに分けようかと思ってます。

■ 意見もらいたい点
- heroの文章で、レスポンシブ考えてspanでinline-block派なんですがどうでしょうか？
- Staff.vueでTs頑張って見ましたが、書き方が不安。。。ってか赤でてる部分の書き方がわからず。

他コメントあればおねがいします。

**Comment by kiaking** [comment]
お願いしまーす！

> slide/History/staffは、今後DBからの取得になるかも？も考慮して、computedで直接書いて実装しましたが、後ほどjsonに分けようかと思ってます。

良いと思います！


> heroの文章で、レスポンシブ考えてspanでinline-block派なんですがどうでしょうか？

禁則処理のためですか？ 特に問題ないです！ そういうこだわりは入れていきたいっすね 👍

**Comment by kiaking** [comment]
一旦実装完了！ 個別タスクがあるので、別途計上する。
