### ISSUE TITLE
Privacy Policyを実装する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#27]
@kazupon こちら使えるテンプレとかありますか？ Vue Fes 2019のものを使って問題なさそうですかね？
https://vuefes.jp/2019/privacy/

**Comment by kazupon** [comment]
@kiaking 
vuejs-jp内では、テンプレはないですね。
google で検索して、いろいろとあるもの参考にベースとして使っても問題ないと思いますが、Vue Fes のものを参考しても大丈夫だと思います。
Vue Fes のときは、前職で CTO してたときに GDPR 対応も盛り込んでいるので。

補足:
Vue Fes のprivacy policyは、個人的情報と cookie policy が盛り込まれていますが、これはこの規模では扱っている個人情報もそれほどないという判断でいっしょにしています。
大きいwebサービス、そして様々なwebサービスと連携している場合は、個人情報のポリシー、cookie のポリシーは分けるが一般的です。

**Comment by kiaking** [comment]
@kazupon 承知しました！ Vue Fesのものを参考にしつつ、「補足」の部分含め、検討して実装できればと思います。

**Comment by kiaking** [comment]
#34 にて実装完了。
