### ISSUE TITLE
markdownの追加

### ISSUE THREAD

**Issue by shiba328** [vuejs-jp/home#29]
markdown-itの追加

**Comment by kiaking** [comment]
@shiba328 Issueありがとうございます！ が、今のところMarkdown使う箇所ってありましたっけ？

**Comment by shiba328** [comment]
@kiaking 行動規範とプラポリはMarkdownのほうが良いかなっと思いました！

**Comment by kiaking** [comment]
@shiba328 おお、なるほど。確かにそうですね。そこはMDで書きますかー。

**Comment by kiaking** [comment]
@shiba328 #33 で行動規範実装時にMarkdownの導入を試みたのですが、ちょっと上手くこう、綺麗に記述する方法で悩み、一旦普通のHTMLで実装しました。

Markdown化することで見通しがよくなりそうなら、導入したいと思っています。誰かが手をつけることを祈りつつ、一旦Enhancement Issueとして置いておきます！

**Comment by kiaking** [comment]
今の所必要ではなくなっているので、一旦クローズします。またMD対応があった方が便利な箇所が出てきたら、検討しましょう！
