### ISSUE TITLE
Site Mapを実装する

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#32]
sitemap.xmlではなく、ページとしてのSite Map。あまりページ数もないので簡単なもので良いと思う。

**Comment by mtmtkzm** [comment]
こちらもらおうかな！とおもいます。

@kiaking デザインカンプって作成予定ありますか？まだなければ、

- インブラウザで @mtmtkzm がやっちゃう
- デザインファイル（ Sketch? Figma? Psd? ）を共有いただき、カンプを作成

どちらでも対応可能かとおもいますがどういたしましょうかー？

**Comment by kiaking** [comment]
@mtmtkzm ありがとうございます！ 現状特にデザインカンプはないですね。なんとなく、こんな感じのシンプルなものを想定していました。
https://www.apple.com/sitemap/

インブラウザでご対応いただければ大丈夫です！
