### ISSUE TITLE
i18nのサポート

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/home#35]
最初は日本語向けなので、必要ないかもしれませんが、今後コミュニティもダイバーシティを意識していきたので、i18nも対応したいところです。
i18n、a11yと双方オーバラップするとこあるので、#31 へもリンク

**Comment by kiaking** [comment]
いいですね！ 海外の人が見て、日本ではこんなコミュニティがあるんだ、と思ってもらえれば嬉しいので僕も多言語対応は賛成です 👍

**Comment by kazupon** [comment]
さてさて、いよいよ i18n 対応しようかと思うんですが、一つ UI 周りで課題が。
言語選択系の UI どうするか問題。

無難に selectbox 使う感じでかね。(vuejs-jp の design system がどうなっているのか分からない問題) /ping @kiaking 
![image](https://user-images.githubusercontent.com/72989/132016789-6b117a50-0b9c-4138-bfac-0a8e610e500e.png)

**Comment by kazupon** [comment]
日本語と英語しかないので、言語選択はこんな感じでtoggle 形式にした。デフォルト初期アクセス時は日本語。
![toggle](https://user-images.githubusercontent.com/72989/132099712-b1779d21-ac5c-4e05-94b9-7662f0719d75.gif)
