### ISSUE TITLE
Webサイト

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/home#4]
Vue Fes はあるけど、vuejs-jp用に欲しい。

**Comment by kazupon** [comment]
#8 で手伝ってくれる方がきたので、内容サイトの内容考える。

**Comment by xiaomoinfo** [comment]
> #8 で手伝ってくれる方がきたので、内容サイトの内容考える。
okです。

**Comment by kahirokunn** [comment]
何卒、自分もお手伝い出来たらと思います 🙏 
一応デザインからサイトを起こしたり、vueのコードをちょっと書けるぐらいのスキルはあるかと思います 🙏

**Comment by kiaking** [comment]
みなさんお待たせしました！ 公式ウェブサイト開発、本格的にスタートします！ つきましては、 #9 を始め、各種Issueを立てたので、是非ともふるってそちらでご協力いただけると幸いです！

最初のうちは特に根幹部分の設計になるのでやりにくい面あると思いますが、遠慮なく本レポジトリのIssueやSlackなでご意見いただければと思います！

よろしくお願いしまーす！ 🤝
