### ISSUE TITLE
一緒にvueで「vuejs-jp」の公式サイトを作ることはどうですか

### ISSUE THREAD

**Issue by xiaomoinfo** [vuejs-jp/home#8]
僕は技術ツリーは「JAVA系のspring、spring boot、spring cloudなど」、web系はangular、vuejsなど。僕ができるなら、やってみよう。

**Comment by kazupon** [comment]
ありがとうございます！
大変うれしいです。
ちょっとサイトの内容考えますので、お待ちください！

**Comment by xiaomoinfo** [comment]
@kazupon はい、承知いたしました。

**Comment by xiaomoinfo** [comment]
> @kazupon 準備は完成したら、僕を呼んでください。

**Comment by kazupon** [comment]
@xiaomoinfo こちら #4 で呼びますね。
