### ISSUE TITLE
Official Website Initial Release

### ISSUE THREAD

**Issue by kiaking** [vuejs-jp/home#9]
Vue.js 日本ユーザーグループの公式ウェブサイトを開発します。当Issueでは、ウェブサイトの初期リリースまでのタスクを洗い出し、トラッキングします。

## タスクリスト

- [x] #13 ドメインを確認する
- [x] #14 ロゴを選定する
- [x] #12 デザインする
- [x] #11 インフラを選定する
- [x] #10 システムを選定する
- [x] #11 #12 グローバルヘッダー/フッターを実装する

> **NOTE:** タスクは開発が進むにつれ、適時追加されていきます。

## 目的

当ウェブサイトの目的を以下に示す。

- Vue.js 日本ユーザーグループが関わるVue.js関連のイベントや、何らかのVue.js関連の情報を日本のVue.jsコミュニティに提供する
- 関西、九州、北海道、東北といったように地域コミュニティも立ちあがりつつあり、各地域のコミュニティも当ウェブサイトの運営に積極的に関われるようにし、日本各地におけるコミュニティ活動を活発化する

## 期日

Vue Fes Japan 2019の開催をターゲットとなる。よって、2019年9月末を目標とする。

## ドメイン

ドメインは `vuejs-jp.org` となる。Vue公式や、Vue Fesなどと統一し、`www`なしの`https://vuejs-jp.org`をURLとする。

## デザイン

Issue #12 でデザイン進行中。

## 開発方針とコンテンツ

上記期日に間に合わせることを第一優先とし、初期リリースでは必要最低限なコンテンツの開発に注力する。必要最低限のコンテンツを以下に列挙する。以下はコンテンツであり、必ずしもページが以下の通りとなる訳ではない点に注意。なお、当然だが実装にはVueを用いる。

- Home
  - Hero
  - コミュニティが提供することの紹介
  - スポンサーの紹介（esa、Slack）
- About
  - コミュニティの紹介、沿革、スタッフなど
- Contact
  - コミュニティへのお問い合わせフォーム
- Legal
  - Privacy Policy
  - Code of Conduct

### 将来的に欲しいコンテンツ

現段階で挙がっている将来的に欲しいコンテンツを以下に列挙する。なお、これらコンテンツは期日に間に合うのであれば初期リリースに取り込んで構わない。

- News
  - 各コミュニティなども含めたニュースの一覧
- Events
  - 各コミュニティなども含めたイベントの一覧と、参加申し込みページへのリンク
- Shop
  - コミュニティ関連グッズが購入できる・・・とか？
- 各コミュニティ紹介
  - 日本で活動するコミュニティの活動との連携

### デザインと実装のつなぎ込みについて

オープンに開発する以上、モックアップベースで正確にデザインから実装に落とし込むのは無理がある（ファイルの共有、作成ツールの統一などを公平に行うのは困難）。そのため、デザインは作成するが、あくまで外観とざっくりとした内容を掴むことを目的とし、細部については実装時に練り込むものとする。

### 開発時の考慮事項

上述の通り、当サイトは継続的にコンテンツ、および機能が追加されていく。そのため、現時点でのコンテンツだけに最適化されたデザイン・実装は避け、いつでも新しいコンテンツの追加・移動・更新・削除が行えるよう心がけた開発を行う。また、各地域コミュニティなど、個別のコミュニティと連携する可能性も視野に入れた上で仕様を検討する必要がある。

## 開発の流れ

現GitHubレポジトリがはんば公式サイトとして機能している面もあるため、`develop`ブランチを切り、そちらで開発を進める。初期リリースのタイミングで`master`へマージすることとする。

## 開発への参加方法

各IssueやSlackなどで自由に意見を述べていただけます。開発へについてもIssueベースで自由に参加いただけます。協力したいがどうすれば良いか分からない場合は、本Issue、Slack、Twitterなどで遠慮なくお声がけください。

**Comment by kazupon** [comment]
改めまして、 @kiaking さん、Webサイトのリードお願いいたします！

**Comment by kkyouhei** [comment]
@kiaking 微力ながらお付き合いさせてください

**Comment by takuyatahata** [comment]
nuxt.jsの参考書にslackのurlが載ってたのですが、どこにあるのでしょうか、検索してもでてきませんでした。仕事でも趣味でも使っていないのですが不親切極まりないですね。
nuxtjs-jp-quapp.comだったとおもいます。quappの部分はpuaqqかな？

**Comment by kiaking** [comment]
@takuyatahata Nuxt.jsの日本語むけSlackチャンネルがある、ということですか？ 個人的には把握しておらず、役に立てそうにありません。すみません。

が、Vue.jsの日本語向けSlackはこちらですよ！ 試してみてはいかがでしょう？
https://vuejs-jp-slackin.herokuapp.com/

**Comment by takuyatahata** [comment]
slackの無料アカウント持ってるんですけど入れないですね。idとパスワード入れてもダメみたいですね。
https://vuejs-jp.slack.com/

**Comment by kiaking** [comment]
@takuyatahata ん？ リンクが違いませんか？ 以下のURLでEmailアドレスを入力すると、招待メールが届くはずです。どうでしょう？
https://vuejs-jp-slackin.herokuapp.com/

**Comment by takuyatahata** [comment]
僕が貼ったurlはそのurlを開いて、下のところにor signとある場所をクリックして飛んだところです

飛ぶ前のページで、僕のe-mailアドレスを入力するとalready_in_team_invited_userとなってました。今メール確認して氏名とパスワード入力して入れたと思います。

**Comment by kiaking** [comment]
おお、そうなんですね。であれば、すでに過去に一度Slackチャンネルに入っている、ということかと思うので、以下のリンクのユーザ名やパスワードを入力するインプットの下部にある「パスワードを忘れた場合」的なリンクをチェックしてみてもらえますか？ 僕は英語で使っているのですが、英語だと「Forgot password?」というやつですね。

**Comment by takuyatahata** [comment]
Forgot password？はどこにあるかわからなかったんですけど
GET MY INVITE→ PLASE WAＩＴ→ SENDING YOU TO SLACKで入れてます。
僕のアカウントこれです。他人からは見られないようになってるんですか？
https://app.slack.com/client/T0X5Y02H0/DP4MWC492/user_profile/UNSCNGFCJ

**Comment by kiaking** [comment]
おお入れたようでなによりです！ Slack上でも確認したので、ダイレクトメッセージをSlackで送ってみました。ようこそ！ Vue.js 日本ユーザーグループへ 👍

**Comment by kiaking** [comment]
ちょっとIssueが形骸化してきた上、トラックしにくいので、Milestoneを作成して、そっちでイニシャルリリースまでの進捗をトラッキングしたいと思います！

**Comment by takuyatahata** [comment]
何かお手伝いできることはありますか？

Mailspring (https://link.getmailspring.com/link/9ADC5EB2-4AF7-4EDD-884D-467ABCD11484@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUo0TEFHVDZJQjdISUI0Q1g3V0xESk40SjJKMkZFVkJOSEhCWVVGNEpBQHJlcGx5LmdpdGh1Yi5jb20%3D)、それは仕事のための最高で無料のメールアプリから送信
